version: "3.8"

services:
  backend:
    image: talhary1/backend-drizzle-express-template:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - PORT=3000
    depends_on:
      - db
    restart: always
    command: sh -c "npm run drizzle:migrate && npm run start:prod"

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
